name: .NET CI

on:
  push:
    branches: [ "main", "develop", "homologacao" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    - name: Listar estrutura
      run: ls -R

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore
      run: dotnet restore $(find . -name "*.sln")

    - name: Build
      run: dotnet build $(find . -name "*.sln") --no-restore --configuration Release

    - name: Test
      run: dotnet test $(find . -name "*.sln") --no-build --verbosity normal
